version: "3"
services:
    # relational database
    postgres:
        hostname: mypostgres
        container_name: postgres_container
        image: 'postgres:14-bullseye'  # latest image as of 2021-11-08
        environment:
            POSTGRES_USER: 'data_analytics'
            POSTGRES_PASSWORD: 'data_analytics'
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - data_analytics_project
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 30s
            timeout: 20s
            retries: 3
    # database administration tool
    pgadmin:
        hostname: mypgadmin
        container_name: pgadmin_container
        image: 'dpage/pgadmin4:6.1'  # latest image as of 2021-11-08
        environment:
            PGADMIN_DEFAULT_EMAIL: 'data_analytics@gmail.com'
            PGADMIN_DEFAULT_PASSWORD: 'data_analytics'
            PGADMIN_CONFIG_SERVER_MODE: 'True'
        volumes:
            - pgadmin:/var/lib/pgadmin4/storage
            - ./data-local:/var/lib/pgadmin/storage/data_analytics_gmail.com:z
        ports:
            - "5050:80"
        networks:
            - data_analytics_project
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://mypgadmin:80/misc/ping"]
            interval: 30s
            timeout: 20s
            retries: 3
volumes:
    postgres:
    pgadmin:

networks:
    data_analytics_project:
        external: true
